services: 
  frontend:
    container_name: frontend
    build: .
    restart: always 
    environment:
      - NODE_ENV=production
    ports:
      - 3000:3000



# run: docker compose -f "compose.prod.yml" up -d --build.