services:
    app:
        container_name: circulate-app
        build:
            context: . #if your Dockerfile is not at the same level change the path here (./frontend)
            target: dev
        image: circulate-app:latest
        restart: always
        command: npm run dev
        environment:
            - NODE_ENV=development
  
        volumes:
            - .:/app
            - /app/node_modules
            - /app/.next
        ports:
            - 3000:3000

# run : docker compose up -d --build